SELECT * FROM R;
SELECT * FROM R WHERE I=100;
SELECT * FROM R WHERE I>100;
SELECT * FROM R JOIN T ON R.K=T.K;
SELECT K,I,C FROM R JOIN T ON R.K=T.K;
SELECT K,sum(B)
FROM R
GROUP BY K;
SELECT C,K
FROM T
ORDER BY C;
SELECT K,sum(C)
FROM R JOIN T ON R.K=T.K
GROUP BY K;
SELECT K,sum(C)
FROM R JOIN T ON R.K=T.K
WHERE K=1
GROUP BY K;
SELECT K,sum(C)
FROM R JOIN T ON R.K=T.K
WHERE C=0
GROUP BY K;
SELECT K,sum(C) AS C
FROM R JOIN T ON R.K=T.K
WHERE C=0
ORDER BY C;
